li = [
    "Thou hast made me endless, such is thy pleasure. This frail vessel thou emptiest again and again, and fillest it ever with fresh life",
    "This little flute of a reed thou hast carried over hills and dales, and hast breathed through it melodies eternally new",
    "At the immortal touch of thy hands my little heart loses its limits in joy and gives birth to utterance ineffable",
    "All that is harsh and dissonant in my life melts into one sweet harmony - and my adoration spreads wings like a glad bird on its flight across the sea",
    "I know thou takest pleasure in my singing. I know that only as a singer I come before thy presence",
    "I touch by the edge of the far-spreading wing of my song thy feet which I could never aspire to reach",
    "Drunk with the joy of singing I forget myself and call thee friend who art my lord",
    "I know not how thou singest, my master! I ever listen in silent amazement",
    "The light of thy music illumines the world The life breath of thy music runs from sky to sky The holy stream of thy music breaks through all stony obstacles and rushes on",
    "I shall ever try to keep all untruths out from my thoughts, knowing that thou art that truth which has kindled the light of reason in my mind",
    "I shall ever try to drive all evils away from my heart and keep my love in flower, knowing that thou hast thy seat in the inmost shrine of my heart",
    "And it shall be my endeavour to reveal thee in my actions, knowing it is thy power gives me strength to act",
    "I ask for a moment's indulgence to sit by thy side. The works that I have in hand I will finish afterwards",
    "Away from the sight of thy face my heart knows no rest nor respite, and my work becomes an endless toil in a shoreless sea of toil",
    "Today the summer has come at my window with its sighs and murmurs; and the bees are plying their minstrelsy at the court of the flowering grove",
    "Now it is time to sit quite, face to face with thee, and to sing dedication of life in this silent and overflowing leisure",
    "Pluck this little flower and take it, delay not! I fear lest it droop and drop into the dust",
    "I may not find a place in thy garland, but honour it with a touch of pain from thy hand and pluck it. I fear lest the day end before I am aware, and the time of offering go by",
    "My poet's vanity dies in shame before thy sight. O master poet, I have sat down at thy feet. Only let me make my life simple and straight, like a flute of reed for thee to fill with music",
    "The child who is decked with prince's robes and who has jewelled chains round his neck loses all pleasure in his play his dress hampers him at every step",
    "In fear that it may be frayed or stained with dust he keeps himself from the world, and is afraid even to move",
    "Mother it is no gain thy bondage of finery if it keeps one shut off from the healthful dust of the earth if it rob one of the right of entrance to the great fair of common human life",
    "O Fool try to carry thyself upon thy own shoulders O beggar to come beg at thy own door",
    "Leave all thy burdens on his hands who can bear all and never look behind in regret",
    "Thy desire at once puts out the light from the lamp it touches with its breath",
    " It is unholy  take not thy gifts through its unclean hands. Accept only what is offered by sacred love",
    "Here is thy footstool and there rest thy feet where live the poorest and lowliest and lost",
    "When I try to bow to thee my obeisance cannot reach down to the depth where thy feet rest among the poorest and lowliest and lost",
    "Pride can never approach to where thou walkest in the clothes of the humble among the poorest and lowliest and lost",
    "My heart can never find its way to where thou keepest company with the companionle"]
